# Generated by Django 4.2.7 on 2023-11-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0002_dailyreport_is_approved_dailyreport_is_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dr.cluster'),
        ),
    ]
