# Generated by Django 4.2.7 on 2023-11-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0006_alter_dailyreport_vibrational_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='vibrational_reading',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='vibrational_reading',
            field=models.ManyToManyField(blank=True, null=True, to='dr.vibrationalreading'),
        ),
    ]
