# Generated by Django 4.2.7 on 2023-11-22 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0008_remove_dailyreport_hse_id_hse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hse',
            name='DailyReport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dr.dailyreport'),
        ),
    ]
