# Generated by Django 4.2.7 on 2023-11-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0009_alter_hse_dailyreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hse',
            old_name='DailyReport',
            new_name='daily_report',
        ),
    ]
