# Generated by Django 4.2.7 on 2023-11-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0010_rename_dailyreport_hse_daily_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hse',
            name='daily_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dr.dailyreport'),
        ),
    ]
