# Generated by Django 4.2.7 on 2023-11-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0011_alter_hse_daily_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='vibrational_reading',
            field=models.ManyToManyField(blank=True, null=True, related_name='vibrational_reading', to='dr.vibrationalreading'),
        ),
    ]
