# Generated by Django 4.2.7 on 2023-11-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0012_alter_dailyreport_vibrational_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('planning', models.IntegerField(blank=True, null=True)),
                ('cumulative_planning', models.IntegerField(blank=True, null=True)),
                ('actual', models.IntegerField(blank=True, null=True)),
                ('proactive', models.IntegerField(blank=True, null=True)),
                ('cumulative_actual', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
