# Generated by Django 4.2.3 on 2023-11-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0014_remove_overallprogress_daily_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overallprogress',
            name='daily_report',
        ),
        migrations.AddField(
            model_name='overallprogress',
            name='daily_report',
            field=models.ManyToManyField(to='dr.dailyreport', verbose_name='daily_report'),
        ),
    ]
