# Generated by Django 4.2.7 on 2023-11-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0015_remove_overallprogress_daily_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallprogress',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overallprogress',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
